/* =====================================================
   ENEM MASTER — Banco de Questões Local (questions.js)
   ~70 questões estilo ENEM com imagens
   Fallback quando api.enem.dev está indisponível
   ===================================================== */

'use strict';

window.LOCAL_QUESTIONS = [

// =====================================================
// CIÊNCIAS HUMANAS (20 questões)
// =====================================================

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA DO BRASIL',
    question: 'A Lei Áurea, assinada em 13 de maio de 1888, aboliu formalmente a escravidão no Brasil. Historiadores, no entanto, argumentam que a abolição não promoveu a integração social dos libertos. Qual medida teria sido mais eficaz para garantir a inclusão real dos ex-escravizados?',
    context: null,
    files: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Assinatura_lei_aurea.jpg/400px-Assinatura_lei_aurea.jpg'],
    quote: null,
    options: [
        'Manter o sistema de parceria nas fazendas para garantir emprego aos libertos.',
        'Distribuir terras e oferecer acesso à educação e ao trabalho digno aos ex-escravizados.',
        'Criar reservas exclusivas para os libertos nas bordas das grandes cidades.',
        'Estabelecer indenização paga aos ex-proprietários de escravos.',
        'Proibir qualquer forma de contrato de trabalho para os ex-escravizados.',
    ],
    correct: 1,
    hint: 'Liberdade formal sem meios concretos (terra, educação, emprego) não garante inclusão real.',
    explanation: 'A abolição sem reforma agrária nem acesso à educação manteve os ex-escravizados em vulnerabilidade, perpetuando as desigualdades raciais e socioeconômicas estruturais do Brasil.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA DO BRASIL',
    question: 'O Ato Institucional Nº 5 (AI-5), de dezembro de 1968, representou o ápice do endurecimento da Ditadura Militar no Brasil. Qual foi a principal consequência do AI-5 para as liberdades individuais e políticas?',
    context: '"O Presidente da República poderá decretar o recesso do Congresso Nacional, das Assembleias Legislativas e das Câmaras de Vereadores." — AI-5, art. 2º, 1968.',
    files: [],
    quote: null,
    options: [
        'Ampliação dos direitos trabalhistas e reconhecimento dos sindicatos.',
        'Realização de eleições diretas para todos os cargos políticos.',
        'Suspensão dos direitos políticos, censura prévia e fechamento do Congresso Nacional.',
        'Início do processo de abertura política e anistia dos exilados.',
        'Criação do FGTS e expansão dos direitos sociais dos trabalhadores.',
    ],
    correct: 2,
    hint: 'O AI-5 marcou o período mais repressivo da ditadura — "golpe dentro do golpe".',
    explanation: 'O AI-5 suspendeu garantias constitucionais, permitiu cassações de mandatos, instaurou censura prévia à imprensa e fechou o Congresso. Deu poderes quase absolutos ao Executivo militar durante os chamados "anos de chumbo".',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA GERAL',
    question: 'A Revolução Francesa (1789) introduziu os ideais de Liberdade, Igualdade e Fraternidade. Entre as primeiras medidas após a queda da Bastilha, qual representou a ruptura mais direta com o Antigo Regime?',
    context: '"Os homens nascem e permanecem livres e iguais em direitos." — Declaração dos Direitos do Homem e do Cidadão, 1789.',
    files: [],
    quote: null,
    options: [
        'A manutenção dos privilégios da nobreza frente ao Terceiro Estado.',
        'A abolição dos direitos feudais e dos privilégios fundamentados no nascimento.',
        'O fortalecimento do poder absoluto do rei Luís XVI sobre a Assembleia.',
        'A expulsão de todos os nobres e clérigos do território francês.',
        'A concentração de terras exclusivamente nas mãos da burguesia.',
    ],
    correct: 1,
    hint: 'O Antigo Regime baseava-se em privilégios hereditários. A Revolução buscou igualdade jurídica.',
    explanation: 'Na noite de 4 de agosto de 1789, a Assembleia aboliu os direitos feudais, eliminando os privilégios da nobreza e do clero e estabelecendo a igualdade perante a lei como princípio jurídico fundamental.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA GERAL',
    question: 'A Segunda Guerra Mundial (1939-1945) terminou com a derrota das potências do Eixo. Qual acontecimento marcou definitivamente o fim do conflito no teatro do Pacífico?',
    context: null,
    files: [],
    quote: null,
    options: [
        'A invasão da Normandia pelos Aliados em junho de 1944.',
        'A rendição incondicional da Alemanha em maio de 1945.',
        'O lançamento das bombas atômicas sobre Hiroshima e Nagasaki em agosto de 1945.',
        'A batalha de Midway, que destruiu a frota japonesa em 1942.',
        'A entrada dos EUA na guerra após Pearl Harbor em 1941.',
    ],
    correct: 2,
    hint: 'O Japão só capitulou após um evento sem precedentes — o uso de armas de destruição em massa.',
    explanation: 'O lançamento das bombas atômicas sobre Hiroshima (6 ago.) e Nagasaki (9 ago.) de 1945 levou à rendição japonesa em 15 de agosto, encerrando o conflito no Pacífico. A decisão ainda provoca intenso debate ético.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA GERAL',
    question: 'A Guerra Fria (1947-1991) foi um conflito geopolítico entre Estados Unidos e URSS marcado por tensão ideológica e corrida armamentista. Qual evento simbolizou mais fortemente o fim da Guerra Fria?',
    context: null,
    files: [],
    quote: null,
    options: [
        'A crise dos mísseis em Cuba em outubro de 1962.',
        'A queda do Muro de Berlim em 1989 e a dissolução da URSS em 1991.',
        'A derrota dos EUA na Guerra do Vietnã em 1975.',
        'A assinatura do Tratado de Não-Proliferação Nuclear em 1968.',
        'A corrida espacial e a chegada do homem à Lua em 1969.',
    ],
    correct: 1,
    hint: 'O símbolo da divisão Leste-Oeste caiu literalmente antes da URSS se dissolver.',
    explanation: 'A queda do Muro de Berlim (1989) e a dissolução da URSS (1991) marcaram o fim da Guerra Fria, da bipolaridade ideológica e do bloco comunista que dominou o pós-guerra.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'FILOSOFIA',
    question: 'Para Immanuel Kant, o imperativo categórico determina que uma ação é moral apenas se puder ser universalizada. Qual alternativa ilustra corretamente esse princípio?',
    context: '"Age apenas segundo uma máxima tal que possas querer que ela se torne lei universal." — Kant, Fundamentação da Metafísica dos Costumes.',
    files: [],
    quote: null,
    options: [
        'Mentir quando isso trouxer maior felicidade ao maior número de pessoas.',
        'Cumprir promessas mesmo quando inconveniente, pois todos deveriam agir assim.',
        'Agir conforme os sentimentos do momento, expressão autêntica da natureza humana.',
        'Praticar o bem apenas quando há perspectiva de recompensa ou reconhecimento.',
        'Obedecer às leis somente quando há risco real de punição.',
    ],
    correct: 1,
    hint: 'Se todos mentissem quando conveniente, a confiança social colapsaria — logo, não é universalizável.',
    explanation: 'Cumprir promessas é universalizável sem contradição. Mentir ou agir por interesse próprio, se universalizados, destruiriam a própria prática que buscam explorar. Para Kant, só o cumprimento do dever é moralmente digno.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'FILOSOFIA',
    question: 'Platão, em "A República", descreve o Mito da Caverna para explicar a relação entre aparência e realidade. O que representam os prisioneiros que só enxergam sombras na parede da caverna?',
    context: 'Prisioneiros acorrentados desde a infância veem apenas sombras projetadas na parede. Confundem essas sombras com a "realidade".',
    files: [],
    quote: null,
    options: [
        'Os filósofos que alcançaram o conhecimento da verdade pela razão.',
        'Os governantes que conduzem a sociedade com base na sabedoria prática.',
        'As pessoas que tomam as aparências sensíveis como única realidade, sem questionar.',
        'Os artistas que criam representações fiéis do mundo inteligível.',
        'Os guerreiros que protegem a cidade dos inimigos externos.',
    ],
    correct: 2,
    hint: 'Quem nunca sai da caverna, segundo Platão? Quem não filosofa.',
    explanation: 'Os prisioneiros representam quem toma o mundo dos sentidos como única realidade. A saída da caverna simboliza o processo filosófico de ascensão ao mundo das Ideias — o conhecimento verdadeiro segundo o idealismo platônico.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'SOCIOLOGIA',
    question: 'Karl Marx afirmou que "a história de toda sociedade até hoje existente é a história de lutas de classes". Qual é a principal causa dos conflitos sociais na sociedade capitalista, segundo o materialismo histórico?',
    context: null,
    files: [],
    quote: null,
    options: [
        'A diferença cultural e religiosa entre grupos étnicos distintos.',
        'A contradição entre burguesia (detentora dos meios de produção) e proletariado (que vende sua força de trabalho).',
        'A preguiça natural dos trabalhadores que se recusam a produzir o suficiente.',
        'A escassez absoluta de recursos naturais que gera competição entre nações.',
        'A ambição individual, traço natural e imutável da natureza humana.',
    ],
    correct: 1,
    hint: 'Para Marx, a base econômica — quem possui os meios de produção — determina os conflitos sociais.',
    explanation: 'No materialismo histórico, o conflito central do capitalismo é a relação de exploração entre burguesia (que detém fábricas, máquinas, capital) e proletariado (que só possui sua força de trabalho e é explorado via extração de mais-valia).',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'SOCIOLOGIA',
    question: 'Émile Durkheim introduziu o conceito de "fato social" como objeto central da Sociologia. Quais são as características que definem um fato social?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Subjetividade, individualidade e dependência da vontade pessoal.',
        'Exterioridade ao indivíduo, coercitividade e generalidade social.',
        'Espontaneidade, criatividade e liberdade de expressão individual.',
        'Materialidade, quantificabilidade e origem nas leis econômicas.',
        'Racionalidade, calculabilidade e orientação exclusiva pelo interesse.',
    ],
    correct: 1,
    hint: 'O fato social existe fora e independe do indivíduo — e o coage a segui-lo.',
    explanation: 'Para Durkheim, fatos sociais são maneiras de agir, pensar e sentir exteriores ao indivíduo, que exercem coerção (pressão para conformidade) e são gerais para toda uma sociedade — como língua, leis e costumes.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'FILOSOFIA',
    question: 'Para John Locke, os seres humanos possuem direitos naturais anteriores ao Estado. Quais são esses direitos que o Estado, criado pelo contrato social, deve proteger?',
    context: 'O contratualismo de Locke influenciou as Revoluções Americana (1776) e Francesa (1789).',
    files: [],
    quote: null,
    options: [
        'Obediência, submissão e segurança garantida pelo soberano absoluto.',
        'Vida, liberdade e propriedade — direitos inalienáveis anteriores ao Estado.',
        'Igualdade, fraternidade e abolição da propriedade privada.',
        'Felicidade, virtude e contemplação da vida boa (eudaimonia aristotélica).',
        'Força, honra e glória, próprios do estado de natureza hobbesiano.',
    ],
    correct: 1,
    hint: 'A Declaração de Independência dos EUA foi diretamente inspirada em Locke: "life, liberty and..."',
    explanation: 'Para Locke, os direitos naturais são vida, liberdade e propriedade. O Estado deriva do consentimento dos governados para proteger esses direitos e perde legitimidade quando os viola — justificando o direito de resistência.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA DO BRASIL',
    question: 'A Semana de Arte Moderna de 1922, realizada no Teatro Municipal de São Paulo, buscava romper com tradições estéticas então dominantes. Contra quais correntes os modernistas se rebelavam?',
    context: '"Tupi or not tupi, that is the question." — Oswald de Andrade, Manifesto Antropófago, 1928.',
    files: [],
    quote: null,
    options: [
        'Contra a herança indígena e africana da cultura brasileira.',
        'Contra as influências europeias e norte-americanas na arte nacional.',
        'Contra o academicismo europeizante e o parnasianismo, propondo arte genuinamente brasileira.',
        'Contra a arte religiosa e conservadora como identidade nacional.',
        'Contra o realismo e o naturalismo como escolas literárias vigentes.',
    ],
    correct: 2,
    hint: 'Os modernistas queriam "devorar" a cultura estrangeira e transformá-la em algo genuinamente brasileiro.',
    explanation: 'A Semana de 22 visou romper com o academicismo e o parnasianismo formal, propondo uma arte que valorizasse os elementos nacionais — fala popular, cultura afro-indígena, humor crítico — com linguagem livre e sem reverência ao passado europeu.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'GEOGRAFIA',
    question: 'O Brasil abriga seis grandes biomas. O bioma com maior biodiversidade do planeta, mas que também concentra o maior volume de desmatamento ilegal em extensão absoluta, é:',
    context: null,
    files: ['https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Biomas_do_brasil.svg/400px-Biomas_do_brasil.svg.png'],
    quote: null,
    options: [
        'Cerrado — berço das águas do Brasil, com as nascentes dos principais rios.',
        'Mata Atlântica — reduzida a menos de 12% de sua cobertura original.',
        'Caatinga — único bioma exclusivamente brasileiro.',
        'Amazônia — mais de 10% de todas as espécies do planeta.',
        'Pampa — caracterizado pelos campos sulinos e pecuária extensiva.',
    ],
    correct: 3,
    hint: 'O maior bioma brasileiro é também o mais rico em biodiversidade e o mais ameaçado em volume absoluto.',
    explanation: 'A Amazônia é o maior bioma e o mais biodiverso do mundo, abrigando mais de 10% das espécies do planeta. Apesar da bioriqueza, enfrenta altas taxas de desmatamento ilegal que ameaçam espécies endêmicas e o equilíbrio climático global.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'GEOGRAFIA',
    question: 'A transição demográfica descreve a mudança nos padrões de natalidade e mortalidade ao longo do desenvolvimento. Em qual fase o Brasil se encontra atualmente, considerando sua taxa de fecundidade abaixo de 1,8 filho por mulher?',
    context: 'Fases: (1) alta natalidade e mortalidade; (2) queda da mortalidade; (3) queda da natalidade; (4) baixas taxas com população envelhecida.',
    files: [],
    quote: null,
    options: [
        'Fase 1: altas taxas de natalidade e mortalidade, população estagnada.',
        'Fase 2: forte queda da mortalidade com manutenção da alta natalidade.',
        'Fase 3 avançada: queda acentuada da natalidade e envelhecimento progressivo.',
        'Fase 4: população em declínio absoluto com natalidade e mortalidade muito baixas.',
        'Pré-transição: nenhuma alteração significativa nas taxas demográficas.',
    ],
    correct: 2,
    hint: 'Taxa de fecundidade abaixo de 2,1 (nível de reposição) + expectativa de vida de 75+ anos = ?',
    explanation: 'O Brasil está na fase 3 avançada: baixas taxas de fecundidade (abaixo do nível de reposição), queda da mortalidade infantil e envelhecimento acelerado da população — com crescente pressão sobre saúde e previdência.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'FILOSOFIA',
    question: 'O utilitarismo, formulado por Bentham e desenvolvido por Mill, propõe que a ação correta maximiza a felicidade do maior número de pessoas. Qual crítica mais frequente é feita a essa teoria?',
    context: null,
    files: [],
    quote: null,
    options: [
        'É muito exigente, pois requer perfeição moral de todos os agentes.',
        'Pode justificar o sacrifício dos direitos de minorias em benefício da maioria.',
        'Ignora completamente as consequências das ações morais.',
        'Está fundamentado exclusivamente em princípios religiosos.',
        'Proíbe qualquer forma de prazer individual ou egoísmo.',
    ],
    correct: 1,
    hint: 'Se 60% da população se beneficia ao prejudicar 40%, o utilitarismo poderia aprovar isso?',
    explanation: 'O utilitarismo pode justificar violar direitos individuais em nome do bem coletivo — como punir um inocente se isso gerar maior utilidade geral. Isso conflita com intuições de justiça e direitos humanos fundamentais.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA GERAL',
    question: 'O Renascimento Cultural (séculos XV-XVI) representou uma ruptura com o teocentrismo medieval e o surgimento do antropocentrismo. Qual foi o principal deslocamento de perspectiva que o Humanismo renascentista promoveu?',
    context: null,
    files: [],
    quote: null,
    options: [
        'A valorização da vida após a morte em detrimento da existência terrena.',
        'A centralidade do ser humano, da razão e da experiência empírica em lugar da fé como critério de conhecimento.',
        'O retorno à autoridade da Igreja Católica como guia do saber.',
        'A recusa de qualquer herança da Antiguidade greco-romana.',
        'A substituição da filosofia pelas ciências exatas como único saber válido.',
    ],
    correct: 1,
    hint: 'O Humanismo coloca o ser humano — não Deus — no centro da reflexão intelectual e artística.',
    explanation: 'O Renascimento promoveu o antropocentrismo: o ser humano passou a ser o referencial de interpretação do mundo. A razão, a experiência e a arte greco-romana foram recuperadas como modelos, em contraposição ao teocentrismo medieval.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA DO BRASIL',
    question: 'A Constituição Federal de 1988, denominada "Constituição Cidadã" por Ulysses Guimarães, foi promulgada após a Ditadura Militar. Qual avanço central ela representou para os direitos do cidadão brasileiro?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Estabeleceu eleições indiretas para presidente e governadores.',
        'Concentrou poderes no Executivo Federal, enfraquecendo o Legislativo.',
        'Ampliou direitos fundamentais, restaurou eleições diretas e criou mecanismos de controle do Estado.',
        'Extinguiu os partidos políticos para garantir estabilidade democrática.',
        'Manteve a censura prévia à imprensa como mecanismo de segurança nacional.',
    ],
    correct: 2,
    hint: '"Cidadã" porque ampliou direitos civis, sociais e políticos ao conjunto da população.',
    explanation: 'A CF-88 restaurou eleições diretas, ampliou os direitos civis, sociais e políticos, criou o habeas data, fortaleceu o Ministério Público e o Judiciário, e estabeleceu a dignidade da pessoa humana como fundamento do Estado democrático.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA GERAL',
    question: 'A Reforma Protestante, iniciada por Martinho Lutero em 1517 com a publicação das 95 Teses, fragmentou a cristandade ocidental. Qual foi a principal crítica inicial de Lutero à Igreja Católica?',
    context: '"A venda de indulgências é uma fraude que ilude o fiel com a promessa de perdão que só Deus pode conceder." — Adaptado de Martinho Lutero.',
    files: [],
    quote: null,
    options: [
        'A adoção do latim, língua inacessível ao povo, nos rituais litúrgicos.',
        'A prática da venda de indulgências e a corrupção institucional da Igreja.',
        'A centralização do poder papal em Roma em detrimento dos bispos locais.',
        'A proibição da leitura da Bíblia em idiomas vernáculos pelos fiéis.',
        'O celibato clerical obrigatório, sem respaldo nas Escrituras.',
    ],
    correct: 1,
    hint: 'As 95 Teses foram redigidas especificamente contra a prática de vender perdões.',
    explanation: 'Lutero criticou diretamente a venda de indulgências (perdões dos pecados em troca de dinheiro) como prática corrupta e teologicamente indefensável. Para ele, a salvação vinha da fé (sola fide), não de obras ou compras — desafiando a autoridade papal.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'HISTÓRIA DO BRASIL',
    question: 'O período colonial brasileiro foi marcado por um ciclo econômico baseado na monocultura e no trabalho escravo. Qual foi o principal ciclo econômico que consolidou a ocupação do interior do Brasil no século XVIII?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Ciclo do açúcar, concentrado no Nordeste.',
        'Ciclo do café, que gerou a industrialização de São Paulo.',
        'Ciclo do ouro, que deslocou o eixo econômico para Minas Gerais.',
        'Ciclo da borracha, que desenvolveu o Norte amazônico.',
        'Ciclo do algodão, que substituiu o açúcar no Nordeste colonial.',
    ],
    correct: 2,
    hint: 'Ouro Preto, Diamantina, Mariana — cidades históricas mineiras — são testemunhas desse ciclo.',
    explanation: 'O ciclo do ouro (séc. XVIII) deslocou o eixo econômico e populacional do Brasil para Minas Gerais. Gerou cidades como Ouro Preto e Mariana, financiou o Barroco brasileiro e provocou a transferência da capital de Salvador para o Rio de Janeiro em 1763.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'SOCIOLOGIA',
    question: 'Max Weber, ao contrário de Marx, considerou que fatores não apenas econômicos determinam a estrutura social. Qual conceito weberiano relaciona a ética protestante ao desenvolvimento do capitalismo?',
    context: '"O espírito do capitalismo" e a ascese protestante criaram uma relação entre trabalho, acumulação e chamado divino.' ,
    files: [],
    quote: null,
    options: [
        'A mais-valia, que descreve a exploração econômica do proletariado.',
        'A "jaula de ferro" da burocracia racional-legal como forma de dominação.',
        'A relação entre a ética protestante (ascese, vocação profissional) e o espírito capitalista.',
        'O conceito de luta de classes como motor da história ocidental.',
        'A divisão do trabalho como fonte de solidariedade orgânica.',
    ],
    correct: 2,
    hint: 'Weber escreveu "A Ética Protestante e o Espírito do Capitalismo" — a tese é exatamente essa.',
    explanation: 'Weber argumentou em "A Ética Protestante e o Espírito do Capitalismo" (1905) que a ascese intramundana calvinista — trabalho como vocação divina, austeridade e reinvestimento dos lucros — foi condição cultural favorável ao surgimento do capitalismo moderno.',
},

{
    area: 'CIÊNCIAS HUMANAS', tag: 'GEOGRAFIA',
    question: 'O fenômeno da urbanização acelerada no Brasil, intensificado a partir de 1950, gerou um perfil demográfico específico. Qual problema social resulta diretamente do processo de urbanização desordenada nas metrópoles brasileiras?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Queda das taxas de natalidade e envelhecimento acelerado da população.',
        'Expansão do agronegócio e concentração fundiária no interior.',
        'Surgimento de periferias com déficit habitacional, violência urbana e falta de saneamento.',
        'Redução das desigualdades regionais pela distribuição de serviços.',
        'Fortalecimento das pequenas cidades como alternativa às metrópoles.',
    ],
    correct: 2,
    hint: 'Êxodo rural massivo + crescimento urbano sem planejamento = quais consequências?',
    explanation: 'A urbanização acelerada sem planejamento gerou periferias superpopulosas com déficit habitacional, falta de saneamento básico, violência urbana e favelização — resultado da migração de populações rurais para cidades sem infraestrutura adequada.',
},

// =====================================================
// CIÊNCIAS DA NATUREZA (20 questões)
// =====================================================

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'Em um cruzamento entre dois indivíduos heterozigotos (Aa × Aa) para uma característica de herança mendeliana simples, qual é a proporção esperada de homozigotos recessivos na prole?',
    context: 'Use o quadro de Punnett para Aa × Aa, considerando dominância completa.',
    files: [],
    quote: null,
    options: [
        '50% (1/2)',
        '75% (3/4)',
        '25% (1/4)',
        '0% — impossível',
        '100% — todos homozigotos',
    ],
    correct: 2,
    hint: 'O quadro de Punnett para Aa × Aa gera: AA, Aa, Aa, aa.',
    explanation: 'No cruzamento Aa × Aa: proporção 1 AA : 2 Aa : 1 aa. Portanto 1/4 (25%) serão homozigotos recessivos (aa).',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'A fotossíntese é o processo pelo qual os produtores convertem energia luminosa em energia química. Qual é o produto principal que armazena essa energia química?',
    context: '6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂',
    files: [],
    quote: null,
    options: [
        'Dióxido de carbono (CO₂)',
        'Água (H₂O)',
        'Oxigênio (O₂), liberado como subproduto',
        'Glicose (C₆H₁₂O₆), armazenando energia química',
        'ATP produzido diretamente pela clorofila',
    ],
    correct: 3,
    hint: 'A glicose é o produto orgânico onde a energia solar fica "guardada" nas ligações químicas.',
    explanation: 'A glicose (C₆H₁₂O₆) armazena a energia solar em suas ligações. O O₂ é subproduto da fotólise da água. CO₂ e H₂O são reagentes.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'A seleção natural, proposta por Darwin, é o mecanismo central da evolução. Qual das premissas é essencial para que ela ocorra?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Todos os indivíduos de uma espécie são geneticamente idênticos.',
        'As variações são aleatórias e não influenciam a sobrevivência.',
        'Organismos com variações vantajosas sobrevivem e reproduzem mais, transmitindo essas variações.',
        'O ambiente permanece constante ao longo do tempo evolucionário.',
        'As espécies não se modificam; apenas os indivíduos mais fortes sobrevivem individualmente.',
    ],
    correct: 2,
    hint: 'Darwin observou: variabilidade + competição + herança = evolução via seleção.',
    explanation: 'A seleção natural requer: (1) variação hereditária entre indivíduos; (2) competição por recursos; (3) vantagem reprodutiva para os mais adaptados. Esses se reproduzem mais, propagando seus genes às gerações seguintes.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'Mitose e meiose são processos de divisão celular com funções distintas. Em qual situação biológica ocorre a meiose e qual é sua importância?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Em células somáticas, para crescimento e reparo de tecidos, mantendo o número cromossômico.',
        'Em células germinativas, produzindo gametas haploides (n) para a reprodução sexual.',
        'Em células tumorais, gerando divisão descontrolada e aneuplodia.',
        'Em bactérias, como processo de reprodução assexuada equivalente à divisão binária.',
        'Exclusivamente em células vegetais para formação de esporos.',
    ],
    correct: 1,
    hint: 'Para a reprodução sexual funcionar, os gametas precisam de metade dos cromossomos — e a meiose garante isso.',
    explanation: 'A meiose nas gônadas produz gametas haploides (n), com metade dos cromossomos da célula-mãe (2n). Na fertilização o número 2n é restaurado. A mitose, em contraste, mantém o número diploide e serve ao crescimento e reparo.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'Qual é a função dos decompositores em um ecossistema?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Capturar energia solar para iniciar a cadeia alimentar.',
        'Consumir herbívoros para regular a população de presas.',
        'Decompor matéria orgânica morta, devolvendo nutrientes inorgânicos ao ambiente.',
        'Transformar CO₂ atmosférico em matéria orgânica por quimiossíntese.',
        'Predar consumidores secundários, controlando a pirâmide ecológica.',
    ],
    correct: 2,
    hint: 'Fungos e bactérias decompositoras reciclam os nutrientes do solo.',
    explanation: 'Os decompositores degradam matéria orgânica morta, mineralizando nutrientes (N, P, K) e devolvendo-os ao ambiente. Sem eles, o ciclo biogeoquímico seria interrompido e os ecossistemas entrariam em colapso.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'As vacinas são um dos maiores avanços da saúde pública. Qual é o mecanismo biológico que explica sua eficácia?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Eliminam diretamente os microrganismos patogênicos do organismo.',
        'Estimulam a produção de anticorpos e memória imunológica sem causar a doença.',
        'Fortalecem células musculares para resistir melhor a infecções.',
        'Substituem células infectadas por células saudáveis do doador.',
        'Elevam a temperatura corporal para eliminar patógenos termossensíveis.',
    ],
    correct: 1,
    hint: 'A vacina "ensina" o sistema imunológico a reconhecer o inimigo antes de encontrá-lo de verdade.',
    explanation: 'As vacinas introduzem antígenos (patógenos atenuados, inativados ou proteínas) que induzem o sistema imune a produzir anticorpos e células de memória. Em contato futuro real, a resposta é rápida e eficaz, prevenindo a doença.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'QUÍMICA',
    question: 'A reação de combustão completa do metano (CH₄) é amplamente usada como fonte de energia. Qual produto gasoso contribui para o efeito estufa?',
    context: 'CH₄ + 2O₂ → CO₂ + 2H₂O',
    files: [],
    quote: null,
    options: [
        'Monóxido de carbono (CO)',
        'Dióxido de carbono (CO₂)',
        'Dióxido de enxofre (SO₂)',
        'Óxido nítrico (NO)',
        'Vapor d\'água (H₂O)',
    ],
    correct: 1,
    hint: 'Na combustão completa, o carbono oxida totalmente. Qual gás resulta?',
    explanation: 'Na combustão completa do CH₄, o carbono é totalmente oxidado a CO₂, principal gás do efeito estufa. O H₂O também é produzido mas não é considerado gás de efeito estufa nas condições normais.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'QUÍMICA',
    question: 'Uma solução tem pH = 3. Se for diluída 10 vezes com água pura, qual será o novo pH aproximado?',
    context: 'pH = −log[H⁺]. Na diluição 1:10, a concentração [H⁺] é dividida por 10.',
    files: [],
    quote: null,
    options: [
        'pH = 0,3',
        'pH = 30',
        'pH = 4',
        'pH = 2',
        'pH = 7 (neutro imediatamente)',
    ],
    correct: 2,
    hint: 'Diluindo 10×: [H⁺] diminui 10×. Como pH = −log[H⁺], o que acontece com o pH?',
    explanation: 'Com pH=3: [H⁺]=10⁻³. Diluindo 10×: [H⁺]=10⁻⁴. Novo pH = −log(10⁻⁴) = 4. Cada diluição por 10 aumenta o pH em 1 unidade.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'QUÍMICA',
    question: 'Qual das substâncias abaixo possui ligação iônica, apresentando alto ponto de fusão e boa solubilidade em água?',
    context: null,
    files: [],
    quote: null,
    options: [
        'O₂ (oxigênio molecular)',
        'C₆H₁₂O₆ (glicose)',
        'NaCl (cloreto de sódio)',
        'CH₄ (metano)',
        'CO₂ (dióxido de carbono)',
    ],
    correct: 2,
    hint: 'Ligações iônicas ocorrem entre metais e não-metais com grande diferença de eletronegatividade.',
    explanation: 'O NaCl possui ligação iônica (transferência de elétrons Na⁺ → Cl⁻), resultando em alto ponto de fusão (801°C) e boa solubilidade em água polar, que estabiliza os íons pelas forças eletrostáticas.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'QUÍMICA',
    question: 'A hidrogenação parcial de óleos vegetais produz gorduras trans. Qual é a principal preocupação de saúde pública associada ao seu consumo regular?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Aumento da produção de insulina e risco de hipoglicemia.',
        'Deficiência de vitaminas D e K por inibição enzimática.',
        'Elevação do colesterol LDL ("ruim") e aumento do risco cardiovascular.',
        'Comprometimento do sistema imunológico por toxicidade celular direta.',
        'Acúmulo de metais pesados no fígado e rins.',
    ],
    correct: 2,
    hint: 'O que os médicos sempre associam a gordura trans e ao coração?',
    explanation: 'As gorduras trans elevam o LDL e reduzem o HDL (colesterol bom), aumentando significativamente o risco de doenças cardiovasculares, aterosclerose e infarto.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'FÍSICA',
    question: 'Um objeto é lançado verticalmente para cima com v₀ = 20 m/s. Com g = 10 m/s², qual é a altura máxima atingida?',
    context: 'No ponto mais alto v = 0. Use: v² = v₀² − 2g·h',
    files: [],
    quote: null,
    options: [
        '10 metros',
        '40 metros',
        '20 metros',
        '5 metros',
        '2 metros',
    ],
    correct: 2,
    hint: 'h = v₀²/(2g) = (20)²/(2×10) = 400/20',
    explanation: '0 = v₀² − 2gh → h = v₀²/(2g) = 400/20 = 20 metros.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'FÍSICA',
    question: 'Um automóvel parte do repouso e atinge 72 km/h em 10 segundos em MUA. Qual é sua aceleração em m/s²?',
    context: '72 km/h = 20 m/s. Para MUA: a = Δv / Δt',
    files: [],
    quote: null,
    options: [
        '7,2 m/s²',
        '0,5 m/s²',
        '2 m/s²',
        '5 m/s²',
        '10 m/s²',
    ],
    correct: 2,
    hint: 'a = (v − v₀) / t = (20 − 0) / 10',
    explanation: 'a = Δv/Δt = (20 − 0)/10 = 2 m/s².',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'FÍSICA',
    question: 'Um satélite em órbita circular ao redor da Terra mantém velocidade escalar constante. Segundo a 1ª Lei de Newton (Lei da Inércia), o que isso indica?',
    context: null,
    files: [],
    quote: null,
    options: [
        'O satélite está em equilíbrio — não age nenhuma força sobre ele.',
        'O satélite obedece plenamente à Lei da Inércia pois sua velocidade é constante.',
        'Há uma força resultante não nula (gravidade) atuando, pois a direção da velocidade varia continuamente.',
        'A inércia é maior em objetos orbitando do que em repouso na superfície.',
        'A lei da inércia não se aplica a objetos no espaço.',
    ],
    correct: 2,
    hint: 'Órbita circular: velocidade escalar constante, mas direção varia — logo, existe aceleração centrípeta.',
    explanation: 'Na órbita circular, a direção do vetor velocidade varia continuamente. Isso constitui aceleração centrípeta, que requer força resultante não nula — a gravidade. Portanto, a 1ª Lei de Newton NÃO se verifica, pois há força resultante.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'FÍSICA',
    question: 'Um fio condutor com R = 5 Ω é conectado a uma bateria de 20 V. Qual é a corrente elétrica que circula pelo fio?',
    context: 'Lei de Ohm: U = R × I',
    files: [],
    quote: null,
    options: [
        '0,25 A',
        '100 A',
        '25 A',
        '4 A',
        '15 A',
    ],
    correct: 3,
    hint: 'Isole I: I = U / R.',
    explanation: 'I = U/R = 20/5 = 4 A.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'FÍSICA',
    question: 'Um raio de luz passa do ar para o vidro e sofre refração. O ângulo de incidência é 60° e o de refração é 37°. Sabendo que n_ar = 1, sen 60° ≈ 0,87 e sen 37° ≈ 0,60, qual é o índice de refração do vidro?',
    context: 'Lei de Snell-Descartes: n₁ × sen θ₁ = n₂ × sen θ₂',
    files: [],
    quote: null,
    options: [
        'n ≈ 0,69',
        'n ≈ 1,45',
        'n ≈ 1,87',
        'n ≈ 2,35',
        'n ≈ 0,51',
    ],
    correct: 1,
    hint: 'n₂ = (n₁ × sen θ₁) / sen θ₂ = (1 × 0,87) / 0,60',
    explanation: 'n_vidro = (1 × 0,87) / 0,60 ≈ 1,45 — consistente com o índice de refração do vidro comum.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'QUÍMICA',
    question: 'Numa reação estequiométrica, 4 g de H₂ reagem com excesso de O₂. Sabendo que H₂ tem massa molar de 2 g/mol, quantos mols de H₂ estão presentes?',
    context: '2H₂ + O₂ → 2H₂O',
    files: [],
    quote: null,
    options: [
        '0,5 mol',
        '2 mol',
        '1 mol',
        '8 mol',
        '4 mol',
    ],
    correct: 1,
    hint: 'n = m / M → n = 4 g / 2 g/mol.',
    explanation: 'n = m/M = 4/2 = 2 mol de H₂. Pela equação, 2 mol H₂ produzem 2 mol H₂O = 36 g de água.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'A biotecnologia moderna utiliza ferramentas de edição genômica como o CRISPR-Cas9. Qual é o princípio básico desta tecnologia?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Amplificação de segmentos de DNA por reação em cadeia da polimerase (PCR).',
        'Corte preciso de sequências específicas de DNA para inserção, deleção ou substituição de genes.',
        'Transferência de núcleos entre ovócitos para clonagem celular.',
        'Análise de perfil genético para investigação forense e paternidade.',
        'Separação de proteínas por eletroforese em gel de agarose.',
    ],
    correct: 1,
    hint: 'CRISPR é uma tesoura molecular — corta o DNA no lugar exato desejado.',
    explanation: 'O CRISPR-Cas9 usa um RNA-guia para levar a proteína Cas9 a uma sequência específica do DNA, onde realiza o corte. Isso permite inserir, deletar ou substituir genes com precisão sem precedentes, com aplicações em medicina, agricultura e pesquisa.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'QUÍMICA',
    question: 'A fotoquímica das camadas da atmosfera envolve a formação e destruição do ozônio. A reação de destruição do ozônio (O₃) por CFCs foi a principal causa do buraco na camada de ozônio. Qual é o papel do CFC nesse processo?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Os CFCs absorvem diretamente o O₃ e o convertem em O₂.',
        'Os CFCs são catalisadores — liberam Cl• que destrói O₃ sem serem consumidos.',
        'Os CFCs reagem com a luz UV para produzir O₃ em excesso.',
        'Os CFCs oxidam o nitrogênio atmosférico que subsequentemente destrói o O₃.',
        'Os CFCs alteram a temperatura da estratosfera, impedindo a formação de O₃.',
    ],
    correct: 1,
    hint: 'Catalisador: participa da reação mas não é consumido. O Cl• liberado pelo CFC age como catalisador.',
    explanation: 'Na estratosfera, a UV fotolisa os CFCs liberando Cl•, que reage com O₃: Cl• + O₃ → ClO + O₂. O ClO libera novamente Cl•, que destrói mais O₃. Um único átomo de cloro pode destruir milhares de moléculas de ozônio.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'FÍSICA',
    question: 'O efeito fotoelétrico, explicado por Einstein em 1905, demonstrou que a luz tem comportamento de partícula (fóton). Qual observação experimental era incompatível com a teoria ondulatória clássica?',
    context: null,
    files: [],
    quote: null,
    options: [
        'A velocidade da luz é constante em qualquer referencial inercial.',
        'A difração da luz ao passar por fendas estreitas.',
        'A emissão de elétrons depende da frequência (não da intensidade) da luz incidente.',
        'A luz pode ser refletida e refratada ao mudar de meio.',
        'A luz sofre interferência construtiva e destrutiva.',
    ],
    correct: 2,
    hint: 'Pela teoria clássica, mais intensidade = mais energia = mais elétrons. Mas os experimentos mostraram algo diferente...',
    explanation: 'A emissão de elétrons depende somente da frequência da luz: abaixo de certa frequência (limiar), nenhum elétron é emitido, independentemente da intensidade. Isso só é explicável admitindo que a luz é quantizada em fótons — cada um com energia E = h·f.',
},

{
    area: 'CIÊNCIAS DA NATUREZA', tag: 'BIOLOGIA',
    question: 'As doenças cardiovasculares são a principal causa de morte no Brasil. Qual fator de risco modificável está mais diretamente associado ao desenvolvimento de aterosclerose?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Histórico familiar de doença cardíaca (fator genético não modificável).',
        'Altos níveis de LDL-colesterol associados à dieta rica em gorduras saturadas e trans.',
        'Baixo nível de escolaridade como indicador socioeconômico.',
        'Grupo sanguíneo tipo A, associado a maior risco cardiovascular.',
        'Exposição a poluentes atmosféricos de partículas grossas (MP10).',
    ],
    correct: 1,
    hint: 'O colesterol LDL forma placas nas artérias — e a dieta influencia diretamente seus níveis.',
    explanation: 'Altos níveis de LDL-colesterol (influenciados por dieta rica em gorduras saturadas e trans, sedentarismo e tabagismo) promovem acúmulo de placas ateroscleróticas nas artérias, elevando o risco de infarto e AVC. É um fator modificável por mudança de hábitos.',
},

// =====================================================
// LINGUAGENS (15 questões)
// =====================================================

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: 'Machado de Assis classificou sua própria narrativa em "Dom Casmurro" (1899) como pertencente ao Realismo. Qual característica do texto machadiano evidencia essa filiação estética?',
    context: 'O narrador Bentinho narra décadas depois os eventos, questionando sua própria confiabilidade. A culpa de Capitu permanece em aberto.',
    files: [],
    quote: null,
    options: [
        'Idealização do amor e heroísmo dos personagens sem ambiguidades morais.',
        'Linguagem rebuscada com preferência por soneto e formas fixas clássicas.',
        'Narrador não confiável, análise psicológica e ironia como instrumento crítico.',
        'Escapismo, valorização do índio e sentimentalismo exacerbado.',
        'Musicalidade simbolista e valorização dos estados de alma acima da ação.',
    ],
    correct: 2,
    hint: 'Machado questiona tudo, inclusive seu próprio narrador. Realismo = olhar crítico sobre o humano.',
    explanation: 'O Realismo machadiano caracteriza-se pelo narrador irônico e não confiável (Bentinho pode estar mentindo ou enganado), análise psicológica profunda dos personagens, crítica social velada e ambiguidade moral — opostos ao romantismo idealizado.',
},

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: 'Euclides da Cunha escreveu "Os Sertões" (1902) sobre a Guerra de Canudos. A obra é considerada precursora do Modernismo. Que visão contraditória do sertanejo Euclides apresenta?',
    context: '"O sertanejo é, antes de tudo, um forte." — Euclides da Cunha, Os Sertões.',
    files: [],
    quote: null,
    options: [
        'O sertanejo como ser inferior e incapaz de integrar a civilização moderna.',
        'O sertanejo como herói épico e símbolo de resistência, ao mesmo tempo que vítima de determinismo racial.',
        'O sertanejo como passivo sem agência histórica ou cultural.',
        'O sertanejo como representante perfeito da elite agrária nordestina.',
        'O sertanejo como resultado positivo da miscigenação racial brasileira.',
    ],
    correct: 1,
    hint: 'Euclides admira a resistência mas também usa a ciência determinista de sua época — tensão presente no texto.',
    explanation: 'Euclides retrata o sertanejo com admiração pela resistência física e moral ("antes de tudo, um forte"), mas também usa o determinismo racial do século XIX, criando uma tensão contraditória. A obra condena o Estado por destruir Canudos.',
},

{
    area: 'LINGUAGENS', tag: 'LINGUAGEM',
    question: 'Analise o verso: "A lua é uma lanterna no telhado do céu." Que figura de linguagem está presente?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Metonímia — substituição de nome por relação de proximidade.',
        'Hipérbole — exagero intencional para intensificar uma ideia.',
        'Metáfora — comparação implícita sem uso de conectivo comparativo.',
        'Eufemismo — suavização de uma realidade desagradável.',
        'Ironia — afirmação de sentido contrário ao intencionado.',
    ],
    correct: 2,
    hint: 'Há comparação entre lua e lanterna, mas sem "como" ou "qual". Isso é...',
    explanation: 'A metáfora identifica dois termos diferentes (lua = lanterna) sem conectivos comparativos, diferente da comparação/símile. Cria uma identidade direta e mais poética entre os elementos.',
},

{
    area: 'LINGUAGENS', tag: 'LINGUAGEM',
    question: 'A variação linguística é um fenômeno natural. Qual é o conceito de "variação diatópica"?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Diferenças na fala de uma mesma pessoa em situações formais e informais.',
        'Variações vocabulares e fonéticas entre falantes de diferentes regiões geográficas.',
        'Mudanças na língua ao longo de séculos (variação histórica/diacrônica).',
        'Diferenças linguísticas entre grupos sociais distintos (variação diastrática).',
        'Variações entre gerações — jovens falando diferente dos idosos.',
    ],
    correct: 1,
    hint: '"Diatópico" = diá (através) + tópos (lugar) = variação por região.',
    explanation: 'A variação diatópica refere-se às diferenças linguísticas entre falantes de regiões distintas — sotaques, vocabulário e entonação que variam de estado a estado ou de país a país. Fundamenta os dialetos regionais.',
},

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: 'O Barroco brasileiro é representado por Gregório de Matos (séc. XVII). Qual característica define o estilo literário barroco?',
    context: '"Neste mundo é mais rico o que mais rua / Tanto tem quanto frauda." — Gregório de Matos.',
    files: [],
    quote: null,
    options: [
        'Linguagem simples, valorização da natureza e do índio idealizado.',
        'Tensão entre opostos (fé × razão, corpo × alma) com estilo rebuscado e uso de antíteses.',
        'Objetividade científica e crítica social realista sem ornamentos.',
        'Musicalidade simbolista com valorização dos estados de alma e sinestesia.',
        'Forma livre e humor irreverente em contestação ao academicismo.',
    ],
    correct: 1,
    hint: 'O Barroco nasceu na era das guerras religiosas — o homem dividido entre sagrado e profano.',
    explanation: 'O Barroco (sécs. XVII-XVIII) marca-se pela tensão entre opostos (corpo vs. alma, amor vs. morte), pelo estilo culteranista com paradoxos, antíteses e hipérboles — reflexo da crise espiritual da Contrarreforma.',
},

{
    area: 'LINGUAGENS', tag: 'ARTES',
    question: 'A obra "A Noite Estrelada" (1889) de Van Gogh é ícone do Pós-Impressionismo. Quais características distinguem esse movimento do Impressionismo?',
    context: null,
    files: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/400px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg'],
    quote: null,
    options: [
        'Representação fotorrealista com detalhes anatômicos precisos.',
        'Uso de cores planas sem gradação, típico da arte medieval.',
        'Pinceladas expressivas e uso emocional da cor para transmitir estados psicológicos.',
        'Fragmentação geométrica da figura em múltiplos planos simultâneos (cubismo).',
        'Abstração total sem referência ao mundo visual.',
    ],
    correct: 2,
    hint: 'Van Gogh não captava apenas a luz — a transformava em emoção com pinceladas em espiral.',
    explanation: 'O Pós-Impressionismo distanciou-se da captação objetiva da luz do Impressionismo para usar cor e forma como expressão emocional. Van Gogh usava pinceladas turbulentas e cores intensas para estados interiores, influenciando o Expressionismo do séc. XX.',
},

{
    area: 'LINGUAGENS', tag: 'ARTES',
    question: '"O Grito" (1893) de Edvard Munch é precursor de qual corrente artística do século XX?',
    context: null,
    files: ['https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/300px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg'],
    quote: null,
    options: [
        'Cubismo — pela fragmentação geométrica.',
        'Surrealismo — pela representação do inconsciente.',
        'Expressionismo — pela distorção das formas para expressar emoções interiores.',
        'Impressionismo — pela captação momentânea da luz.',
        'Neoclassicismo — pelo retorno à estética greco-romana.',
    ],
    correct: 2,
    hint: 'A figura gritante com céu turbulento não retrata o mundo exterior, mas a angústia interior.',
    explanation: '"O Grito" deforma paisagem e figura para expressar angústia existencial, prenunciando o Expressionismo (início do séc. XX), que prioriza a emoção subjetiva, usando distorção, cores intensas e formas angulosas para representar estados psicológicos.',
},

{
    area: 'LINGUAGENS', tag: 'LINGUAGEM',
    question: 'Qual recurso linguístico é central para a leitura crítica de charges políticas?',
    context: null,
    files: [],
    quote: null,
    options: [
        'O uso exclusivo de linguagem técnica e formal para crítica objetiva.',
        'A ironia, que permite criticar ao dizer algo para significar o oposto.',
        'A reprodução fiel e objetiva dos fatos noticiados.',
        'A metonímia como substituição do político pelo cargo.',
        'A hipérbole gramatical para enfatizar a beleza da linguagem.',
    ],
    correct: 1,
    hint: 'A charge diz uma coisa mas quer significar outra — que figura é essa?',
    explanation: 'A ironia é central nas charges: o cartunista afirma algo para significar o oposto, ou exagera para revelar absurdos da realidade política. A compreensão exige conhecer o contexto social e político referenciado.',
},

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: 'O Romantismo brasileiro (1836-1881) caracterizou-se pela idealização do índio como símbolo da nação. Qual obra de José de Alencar é o exemplo mais representativo dessa corrente indianista?',
    context: null,
    files: [],
    quote: null,
    options: [
        '"O Cortiço" — Aluísio Azevedo.',
        '"Iracema" — José de Alencar.',
        '"Memórias Póstumas de Brás Cubas" — Machado de Assis.',
        '"Os Sertões" — Euclides da Cunha.',
        '"Vidas Secas" — Graciliano Ramos.',
    ],
    correct: 1,
    hint: 'Iracema é uma índia, sua história é um mito de fundação do Brasil — ideal romântico.',
    explanation: '"Iracema" (1865), de Alencar, é o exemplo máximo do Indianismo romântico: a índia Iracema representa a alma do Brasil, o amor puro e o sacrifício pela pátria em formação — idealização típica do Romantismo.',
},

{
    area: 'LINGUAGENS', tag: 'LINGUAGEM',
    question: 'Em redação dissertativa-argumentativa do ENEM, qual é a função do parágrafo de conclusão?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Apresentar novos argumentos não abordados no desenvolvimento.',
        'Repetir a tese e os argumentos de forma idêntica ao desenvolvimento.',
        'Retomar a tese, sintetizar os argumentos e apresentar proposta de intervenção detalhada.',
        'Introduzir o tema e contextualizar o leitor.',
        'Apresentar dados estatísticos que comprovem os argumentos.',
    ],
    correct: 2,
    hint: 'A conclusão fecha o texto: tese + síntese + proposta de intervenção social.',
    explanation: 'Na ENEM, a conclusão deve: retomar a tese de forma sintética, resumir os argumentos e apresentar proposta de intervenção social detalhada (com agente, ação, meio, finalidade e efeito esperado).',
},

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: 'O Simbolismo, surgido na França no final do séc. XIX, influenciou a poesia brasileira. Qual poeta é considerado o maior representante do Simbolismo no Brasil?',
    context: '"Ora (direis) ouvir estrelas! / Certo / Perdeste o senso!" E eu vos direi, no entanto, / Que para ouvi-las foi preciso estar em silêncio. — Olavo Bilac (Parnasianismo)',
    files: [],
    quote: null,
    options: [
        'Olavo Bilac — Parnasianismo.',
        'João Cabral de Melo Neto — Concretismo.',
        'Cruz e Sousa — Simbolismo.',
        'Manuel Bandeira — Modernismo.',
        'Gonçalves Dias — Romantismo.',
    ],
    correct: 2,
    hint: 'Cruz e Sousa foi negro e catarinense, chamado de "Dante Negro" — representante máximo do Simbolismo.',
    explanation: 'Cruz e Sousa (1861-1898) é o maior representante do Simbolismo brasileiro. Sua poesia usa musicalidade, sinestesia e metáforas sensoriais para evocar o mundo espiritual e subjetivo — marca central do Simbolismo.',
},

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: 'O Modernismo brasileiro de 1922 propôs uma ruptura com os padrões estéticos vigentes. Qual característica marca a Primeira Fase Modernista (1922-1930)?',
    context: '"Tupi or not tupi, that is the question." — Oswald de Andrade, Manifesto Antropófago.',
    files: [],
    quote: null,
    options: [
        'Valorização da linguagem culta e das formas fixas como o soneto.',
        'Idealização do índio como símbolo de pureza nacional.',
        'Ruptura com a norma culta, humor, ironia e valorização da cultura popular brasileira.',
        'Introspecção psicológica e análise do comportamento urbano.',
        'Exaltação do progresso industrial como salvação da humanidade.',
    ],
    correct: 2,
    hint: 'A Semana de 22 foi provocativa, irreverente, anti-academicista — valorizou o que é brasileiro.',
    explanation: 'A 1ª Fase Modernista rompeu com o academicismo, usou linguagem coloquial, humor e ironia, e valorizou a cultura popular brasileira — como no Manifesto Antropófago de Oswald, que propunha "devorar" a cultura europeia para criar algo novo.',
},

{
    area: 'LINGUAGENS', tag: 'LINGUAGEM',
    question: 'A partir da análise da linguagem publicitária, qual recurso argumentativo é mais comum na construção do ethos (imagem de credibilidade) de uma marca?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Uso de dados estatísticos refutáveis para criar aparência científica.',
        'Associação da marca a especialistas, celebridades ou valores positivos admirados pelo público.',
        'Ameaças veladas ao consumidor que não adere ao produto.',
        'Argumentos ad hominem que atacam marcas concorrentes.',
        'Uso exclusivo de linguagem técnica inacessível ao público leigo.',
    ],
    correct: 1,
    hint: 'Ethos = credibilidade. Como se constrói credibilidade rapidamente?',
    explanation: 'O ethos publicitário é construído pela associação a figuras de autoridade (médicos, especialistas), celebridades admiradas ou valores coletivos positivos (sustentabilidade, família, saúde). Essa associação transfere credibilidade e desejo ao produto.',
},

{
    area: 'LINGUAGENS', tag: 'LITERATURA',
    question: '"Vidas Secas" (1938) de Graciliano Ramos é um clássico do Modernismo brasileiro da 2ª Fase (Regionalismo). O que a narrativa denuncia principalmente?',
    context: '"Fabiano olhou o céu, a terra, o homem. Bestializou-se." — Adaptado de Graciliano Ramos.',
    files: [],
    quote: null,
    options: [
        'A decadência da aristocracia rural do café no interior de São Paulo.',
        'As migrações europeias e as tensões culturais no sul do Brasil.',
        'As condições desumanas de vida no sertão nordestino e a exclusão social dos retirantes.',
        'A industrialização e a alienação do operário nas grandes cidades.',
        'O êxodo rural e a chegada dos migrantes nordestinos a São Paulo.',
    ],
    correct: 2,
    hint: 'Fabiano, Sinhá Vitória e os filhos sem nome fogem da seca — o que isso simboliza?',
    explanation: '"Vidas Secas" denuncia as condições desumanas do sertão nordestino: seca, latifúndio, exploração e exclusão. A família de Fabiano retirante representa milhões excluídos das benesses do país. O romance usa técnica do monólogo interior fragmentado.',
},

{
    area: 'LINGUAGENS', tag: 'ARTES',
    question: 'A arte rupestre (pinturas em cavernas) é uma das formas mais antigas de manifestação artística humana. O que essas representações revelam sobre as sociedades pré-históricas?',
    context: null,
    files: [],
    quote: null,
    options: [
        'Que os humanos pré-históricos não tinham capacidade simbólica.',
        'Que a arte era exclusivamente decorativa e sem significado social.',
        'Que havia pensamento simbólico, rituais e capacidade de representação do mundo.',
        'Que essas sociedades já tinham escrita e comunicação verbal complexa.',
        'Que a arte rupestre era produzida exclusivamente por mulheres.',
    ],
    correct: 2,
    hint: 'Pintar animais em cavernas exige representação mental — simbolismo e ritualidade.',
    explanation: 'A arte rupestre evidencia pensamento simbólico avançado, rituais (provavelmente mágico-religiosos ligados à caça), coesão social e capacidade de abstração. Representa a emergência da cultura humana muito antes da escrita.',
},

// =====================================================
// MATEMÁTICA (15 questões)
// =====================================================

{
    area: 'MATEMÁTICA', tag: 'FUNÇÕES',
    question: 'A função do 2º grau f(x) = x² − 4x + 3 possui duas raízes reais. Quais são elas?',
    context: 'Use Bhaskara: x = (−b ± √Δ) / 2a, onde Δ = b² − 4ac.',
    files: [],
    quote: null,
    options: [
        'x = 1 e x = 3',
        'x = −1 e x = −3',
        'x = 2 e x = 4',
        'x = 0 e x = 4',
        'x = 1 e x = −3',
    ],
    correct: 0,
    hint: 'Δ = 16 − 12 = 4. x = (4 ± 2)/2.',
    explanation: 'Com a=1, b=−4, c=3: Δ=4, √Δ=2. x₁=(4+2)/2=3, x₂=(4−2)/2=1. Raízes: x=1 e x=3.',
},

{
    area: 'MATEMÁTICA', tag: 'GEOMETRIA',
    question: 'Um terreno retangular tem 30 m de comprimento e 20 m de largura. Qual é a medida da diagonal?',
    context: 'Teorema de Pitágoras: d² = a² + b²',
    files: [],
    quote: null,
    options: [
        '25 metros',
        '50 metros',
        '36 metros',
        '10√13 metros',
        '600 metros',
    ],
    correct: 3,
    hint: 'd² = 30² + 20² = 900 + 400 = 1300 → d = √1300 = 10√13',
    explanation: 'd = √(900+400) = √1300 = 10√13 ≈ 36,06 metros.',
},

{
    area: 'MATEMÁTICA', tag: 'PORCENTAGEM',
    question: 'Uma loja oferece 20% de desconto em um produto de R$ 350,00. Qual é o valor final a ser pago?',
    context: null,
    files: [],
    quote: null,
    options: [
        'R$ 280,00',
        'R$ 70,00',
        'R$ 330,00',
        'R$ 310,00',
        'R$ 420,00',
    ],
    correct: 0,
    hint: 'Desconto = 20% × 350 = 70. Valor final = 350 − 70.',
    explanation: 'Desconto = 0,20 × 350 = R$ 70. Valor final = R$ 350 − 70 = R$ 280,00.',
},

{
    area: 'MATEMÁTICA', tag: 'PROGRESSÃO ARITMÉTICA',
    question: 'Em uma PA com a₁ = 3 e razão r = 5, qual é o 8º termo?',
    context: 'Fórmula do termo geral: aₙ = a₁ + (n−1)·r',
    files: [],
    quote: null,
    options: [
        '35',
        '38',
        '40',
        '43',
        '45',
    ],
    correct: 1,
    hint: 'a₈ = 3 + (8−1)×5 = 3 + 35.',
    explanation: 'a₈ = 3 + 7×5 = 3 + 35 = 38.',
},

{
    area: 'MATEMÁTICA', tag: 'PROBABILIDADE',
    question: 'Uma urna contém 4 bolas vermelhas, 3 azuis e 3 brancas. Retira-se uma ao acaso. Qual é a probabilidade de ser azul?',
    context: 'P(A) = casos favoráveis / total de casos',
    files: [],
    quote: null,
    options: [
        '1/3',
        '3/10',
        '4/10',
        '3/7',
        '1/10',
    ],
    correct: 1,
    hint: 'Total = 4+3+3 = 10 bolas. Azuis = 3.',
    explanation: 'P(azul) = 3/10 = 0,3 ou 30%.',
},

{
    area: 'MATEMÁTICA', tag: 'ESTATÍSTICA',
    question: 'As notas de 5 alunos foram: 6, 7, 8, 9 e 10. Qual é a média aritmética simples?',
    context: 'Média = soma / quantidade',
    files: [],
    quote: null,
    options: [
        '7,5',
        '8,0',
        '8,5',
        '9,0',
        '7,0',
    ],
    correct: 1,
    hint: 'Soma = 6+7+8+9+10 = 40. Média = 40/5.',
    explanation: 'Média = 40/5 = 8,0.',
},

{
    area: 'MATEMÁTICA', tag: 'TRIGONOMETRIA',
    question: 'Em um triângulo retângulo, o ângulo α = 30° e o cateto adjacente mede 6 cm. Qual é o comprimento da hipotenusa? (cos 30° = √3/2)',
    context: 'cos α = cateto adjacente / hipotenusa',
    files: [],
    quote: null,
    options: [
        '3 cm',
        '6 cm',
        '6√3 cm ≈ 10,4 cm',
        '4√3 cm ≈ 6,93 cm',
        '12 cm',
    ],
    correct: 3,
    hint: 'hipotenusa = cateto adjacente / cos 30° = 6 / (√3/2) = 12/√3 = 4√3',
    explanation: 'hipotenusa = 6 ÷ (√3/2) = 6 × (2/√3) = 12/√3 = 12√3/3 = 4√3 ≈ 6,93 cm.',
},

{
    area: 'MATEMÁTICA', tag: 'GEOMETRIA',
    question: 'Um cilindro tem raio r = 3 cm e altura h = 10 cm. Qual é seu volume? (π ≈ 3,14)',
    context: 'Volume do cilindro: V = π × r² × h',
    files: [],
    quote: null,
    options: [
        '94,2 cm³',
        '282,6 cm³',
        '188,4 cm³',
        '56,52 cm³',
        '314 cm³',
    ],
    correct: 1,
    hint: 'V = π × 9 × 10',
    explanation: 'V = 3,14 × 3² × 10 = 3,14 × 9 × 10 = 282,6 cm³.',
},

{
    area: 'MATEMÁTICA', tag: 'FUNÇÕES',
    question: 'Uma colônia de bactérias dobra a cada 30 minutos. Partindo de 100 bactérias, quantas haverá após 2 horas?',
    context: 'N(t) = N₀ × 2^(t/30), com t em minutos.',
    files: [],
    quote: null,
    options: [
        '400 bactérias',
        '800 bactérias',
        '1.200 bactérias',
        '1.600 bactérias',
        '3.200 bactérias',
    ],
    correct: 3,
    hint: '2 horas = 120 min. Duplicações = 120/30 = 4.',
    explanation: '4 duplicações: N = 100 × 2⁴ = 100 × 16 = 1.600 bactérias.',
},

{
    area: 'MATEMÁTICA', tag: 'COMBINATÓRIA',
    question: 'Quantas senhas de 3 dígitos distintos podem ser formadas com {1, 2, 3, 4, 5}, sem repetição?',
    context: 'Arranjo simples: Aⁿₚ = n! / (n−p)! (a ordem importa)',
    files: [],
    quote: null,
    options: [
        '10',
        '60',
        '125',
        '15',
        '120',
    ],
    correct: 1,
    hint: 'A⁵₃ = 5 × 4 × 3',
    explanation: 'A⁵₃ = 5!/(5−3)! = 5×4×3 = 60 senhas.',
},

{
    area: 'MATEMÁTICA', tag: 'LOGARITMOS',
    question: 'Dado que log₁₀ 2 = 0,30, qual é o valor de log₁₀ 8?',
    context: 'Propriedade: log(aⁿ) = n × log(a)',
    files: [],
    quote: null,
    options: [
        '0,60',
        '0,90',
        '0,24',
        '2,40',
        '0,80',
    ],
    correct: 1,
    hint: '8 = 2³ → log 8 = 3 × log 2',
    explanation: 'log₁₀ 8 = log₁₀ 2³ = 3 × 0,30 = 0,90.',
},

{
    area: 'MATEMÁTICA', tag: 'GEOMETRIA ANALÍTICA',
    question: 'Dois pontos no plano cartesiano: A(1, 2) e B(4, 6). Qual é a distância entre eles?',
    context: 'd = √[(x₂−x₁)² + (y₂−y₁)²]',
    files: [],
    quote: null,
    options: [
        'd = 5',
        'd = 7',
        'd = 25',
        'd = √7',
        'd = 12',
    ],
    correct: 0,
    hint: 'Δx = 3, Δy = 4. d = √(9+16) = √25',
    explanation: 'd = √(3² + 4²) = √(9+16) = √25 = 5.',
},

{
    area: 'MATEMÁTICA', tag: 'PROGRESSÃO GEOMÉTRICA',
    question: 'Em uma PG com a₁ = 2 e razão q = 3, qual é a soma dos 4 primeiros termos?',
    context: 'Sₙ = a₁ × (qⁿ − 1) / (q − 1)',
    files: [],
    quote: null,
    options: [
        '80',
        '78',
        '81',
        '62',
        '26',
    ],
    correct: 0,
    hint: 'Os 4 termos: 2, 6, 18, 54. Soma = ?',
    explanation: '2 + 6 + 18 + 54 = 80.',
},

{
    area: 'MATEMÁTICA', tag: 'JUROS',
    question: 'R$ 1.000,00 aplicados a juros simples de 2% ao mês. Qual o montante após 6 meses?',
    context: 'Juros simples: M = C × (1 + i × t)',
    files: [],
    quote: null,
    options: [
        'R$ 1.020,00',
        'R$ 1.126,16',
        'R$ 1.200,00',
        'R$ 1.120,00',
        'R$ 1.060,00',
    ],
    correct: 3,
    hint: 'M = 1000 × (1 + 0,02 × 6) = 1000 × 1,12',
    explanation: 'M = 1000 × (1 + 0,12) = R$ 1.120,00.',
},

{
    area: 'MATEMÁTICA', tag: 'ESTATÍSTICA',
    question: 'Em um conjunto de dados {3, 5, 7, 7, 9, 11, 11, 11, 15}, qual é a moda?',
    context: 'Moda = valor(es) que aparecem com maior frequência.',
    files: [],
    quote: null,
    options: [
        '7',
        '9',
        '11',
        '3 e 11',
        'Não existe moda (amodal)',
    ],
    correct: 2,
    hint: 'Conte quantas vezes cada valor aparece: 11 aparece 3 vezes.',
    explanation: 'O valor 11 aparece 3 vezes, a maior frequência do conjunto. Portanto, a moda é 11.',
},

]; // fim de window.LOCAL_QUESTIONS
